---
layout: cv
title: Caleb Gardner's CV
---
# Caleb Gardner
Accounting Student.

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Data analytics and tax preparation professional, leveraging modern tools and AI to optimize financial processes.

## Specialized in

Taxes

## Research interests

Trust returns, data analytics, generative AI tools, process efficiency, SQL, Python.

## Education

`2023 - 2027`
__Brigham Young University–Idaho__

- Bachelor of Science in Accounting (Cumulative GPA: 3.94)
- Minor: Data Analytics
- Intend to complete Master of Science in Accounting by December 2027

## Experience

`2026 - 2026`
__Tax Intern__, Forvis Mazars (Kansas City, MO)

- Prepared over 45 tax returns including forms 1040, 1041, 1120, 1120S, and 1065
- Developed a specialization in trust returns
- Analyzed state and federal tax notices for clients to resolve outstanding IRS balances
- Partnered with engagement executives to serve clients in real estate, agriculture, and investing sectors

`2025 - 2025`
__PR Officer__, Student Accounting Society (Rexburg, ID)

- Maintained and initiated contact with potential SAS presenters
- Coordinated all presentations and guest speakers for society meetings of 120+ members
- Managed weekly event announcements

`2025 - 2026`
__Process Assistant__, PEG Companies (Remote)

- Documented over 50 vital company processes, improving efficiency and security
- Organized and led meetings between key stakeholders
- Leveraged a variety of generative AI tools to complete complex and sizable tasks

`2023 - 2025`
__Quotas team, Supervisor, Dialer__, Clear Insights (Rexburg, ID)

- Managed survey research project staffing for five total call centers and more than 200 employees
- Motivated workers with positive reinforcement and a good attitude
- Finished pay periods as a top 5 dialer 15+ times

`2021 - 2023`
__Full-Time Volunteer Representative__, The Church of Jesus Christ of Latter-day Saints (Northern Utah)

- Led groups of volunteers to help them make plans to accomplish goals
- Committed approximately 100 hours per week for two years, unpaid
- Developed communication and leadership skills

<!-- ### Footer

Last updated: May 2013 -->